version: "3.8"

services:
  # ============================
  #         ZOOKEEPER
  # ============================
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bigdata

  # ============================
  #            KAFKA
  # ============================
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - bigdata

  # ============================
  #       HDFS CLUSTER
  # ============================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    networks:
      - bigdata

  datanode-a:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-a
    hostname: datanode-a
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - ./hdfs/datanode-a:/hadoop/dfs/data
    networks:
      - bigdata

  datanode-b:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-b
    hostname: datanode-b
    restart: always
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    volumes:
      - ./hdfs/datanode-b:/hadoop/dfs/data
    networks:
      - bigdata

  # ============================
  #         PRODUCER APP
  # ============================
  producer-app:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer-app
    environment:
      - KAFKA_BROKER=kafka-broker:9092
    depends_on:
      - kafka
      - namenode
    networks:
      - bigdata
  
  # ============================
  #       SPARK MASTER
  # ============================
  spark-master:
    build:
      context: ./spark-processing
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - bigdata
    gpus: all

  # ============================
  #       SPARK WORKERS
  # ============================
  spark-worker-1:
    build:
      context: ./spark-processing
    container_name: spark-worker-1
    hostname: worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - bigdata
    gpus: all

  spark-worker-2:
    build:
      context: ./spark-processing
    container_name: spark-worker-2
    hostname: worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - bigdata
    gpus: all

  spark-worker-3:
    build:
      context: ./spark-processing
    container_name: spark-worker-3
    hostname: worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - bigdata
    gpus: all

networks:
  bigdata:
    driver: bridge
